name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "APP_ADDR=${{ secrets.APP_ADDR }}" >> .env
          echo "CA_PEM_PATH=./tls/ca.pem" >> .env
          echo "CERT_PEM_PATH=./tls/cert.pem" >> .env
          echo "KEY_PEM_PATH=./tls/key.pem" >> .env

      - name: Decode TLS files
        run: |
          mkdir -p tls
          echo "${{ secrets.CA_PEM_PATH }}" | base64 -d > tls/ca.pem
          echo "${{ secrets.CERT_PEM_PATH }}" | base64 -d > tls/cert.pem
          echo "${{ secrets.KEY_PEM_PATH }}" | base64 -d > tls/key.pem

      - name: Debug TLS files
        run: ls -l tls/

      - name: Install dependencies
        run: go mod tidy

      - name: Build the application
        run: go build -o app ./cmd/web

      - name: Run tests
        run: go test ./...

      - name: Run the application
        run: ./app